import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Logo from "../../public/logo.svg";
import MenuIcon from "../assets/icons/menu.svg";
import MailIcon from "../assets/icons/mail.svg";
import PhoneIcon from "../assets/icons/phone.svg";
import Linkedin from "../assets/icons/linkedin.svg";
import HeroImage from "../assets/imgs/Hero.png";
import Logo2 from "../assets/imgs/logo2.svg";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="absolute top-0 left-0 right-0 z-10 bg-transparent">
          <div className="flex flex-row flex-wrap justify-between items-center mx-16 my-7">
            <Link href="/">
              <Image
                src={Logo}
                alt="furchase logo"
                className="w-full h-auto max-w-[190px] cursor-pointer"
              />
            </Link>
            <div className="flex flex-row flex-wrap items-center">
              <button className="text-accent px-6 py-2.5 border border-dark-white mr-6 cursor-pointer">
                Private Inquiry
              </button>
              <div className="p-4 cursor-pointer">
                <Image
                  src={MenuIcon}
                  alt="menu icon"
                  width={16}
                  height={12}
                  className="block"
                />
              </div>
            </div>
          </div>

          {/* <nav>
            <Link href="#">About Us</Link>
            <Link href="#">Contact us</Link>
            <Link href="#">Blog</Link>
            <Link href="#">FAQ</Link>
          </nav> */}
        </header>
        <div className="relative z-0">
          <Image
            src={HeroImage}
            width={1440}
            height={900}
            alt="hero banner"
            className="w-full "
          />
          <h1 className="absolute top-[55%] left-[27%] -translate-x-1/2 -translate-y-1/2 w-[560px] h-[172px] text-heading-1 text-accent uppercase">
            financial ecosystem
          </h1>
        </div>
        {children}
        <div className="max-w-1440 mx-auto"></div>
        <footer>
          <div className="py-10 px-16 bg-primary">
            <div className="flex flex-row flex-wrap items-center justify-between max-w-1440 mx-auto">
              <span className="text-display-xxl text-accent">Get in touch</span>
              <div className="flex flex-col gap-6 justify-center items-center">
                <Image src={MailIcon} width={34} height={27} alt="mail icon" />
                <a
                  href="mailto:"
                  className="text-accent underline text-button-m"
                >
                  hello@fuchase.com
                </a>
              </div>
              <div className="flex flex-col gap-6 justify-center items-center">
                <Image src={PhoneIcon} width={30} height={30} alt="mail icon" />
                <a href="tel:+" className="text-accent underline text-button-m">
                  +1 (555) 000-0000
                </a>
              </div>
            </div>
          </div>
          <div className="px-16 pb-20 bg-secondary">
            <div className="py-14 flex flex-row flex-wrap justify-between max-w-1440 mx-auto">
              <div className="flex flex-col flex-wrap items-center gap-7">
                <Image src={Logo2} width={196} height={123} alt="logo2" />
                <a href="http://">
                  <Image
                    src={Linkedin}
                    width={30}
                    height={30}
                    alt="linkedin icon"
                    className="cursor-pointer"
                  />
                </a>
              </div>
              <div className="flex flex-row flex-wrap justify-between items-center gap-36">
                <ul>
                  <li className="text-display-xl text-accent pb-3">Company</li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      About
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Our Services
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Careers
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-display-l text-accent">
                      Our History
                    </Link>
                  </li>
                </ul>
                <ul>
                  <li className="text-display-xl text-accent pb-3">Company</li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      About
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Our Services
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Careers
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-display-l text-accent">
                      Our History
                    </Link>
                  </li>
                </ul>
                <ul>
                  <li className="text-display-xl text-accent pb-3">Company</li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      About
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Our Services
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Careers
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-display-l text-accent">
                      Our History
                    </Link>
                  </li>
                </ul>
                <ul>
                  <li className="text-display-xl text-accent pb-3">Company</li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      About
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Our Services
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Careers
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-display-l text-accent">
                      Our History
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
            <hr className="border border-dark-white" />
            <div className="py-2.5 flex flex-row flex-wrap justify-between items-center">
              <span className="block text-accent text-display-l">
                @2026 Fuchase
              </span>
              <p className="max-w-[741px] text-accent text-display-l">
                We connect elite financial institutions and visionary investors
                with transformative opportunities, exclusive partnerships, and
                next-generation financial infrastructure designed for those who
                operate at the highest level of global finance.{" "}
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
