import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Logo from "../../public/logo.svg";
import MenuIcon from "../assets/icons/menu.svg";
import MailIcon from "../assets/icons/mail.svg";
import PhoneIcon from "../assets/icons/phone.svg";
import Linkedin from "../assets/icons/linkedin.svg";
import HeroImage from "../assets/imgs/Hero.png";
import Logo2 from "../assets/imgs/logo2.svg";
import BlackRockLogo from "../assets/imgs/blackrock.png";
import CreditSuisse from "../assets/imgs/creditsuisse.png";
import GoldmanSachs from "../assets/imgs/goldmansachs.png";
import JpMorgan from "../assets/imgs/jpmorgan.png";
import MorganStanley from "../assets/imgs/morganstanley.png";
import Section1 from "../assets/imgs/section1.png";
import Section2 from "../assets/imgs/section2.png";
import Ornament from "../assets/imgs/ornament.png";
import Location from "../assets/icons/location.svg";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const partners = [
  BlackRockLogo,
  CreditSuisse,
  GoldmanSachs,
  JpMorgan,
  MorganStanley,
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* header */}
        <header className="absolute top-0 left-0 right-0 z-10 bg-transparent">
          <div className="flex flex-row flex-wrap justify-between items-center mx-16 my-7">
            <Link href="/">
              <Image
                src={Logo}
                alt="furchase logo"
                className="w-full h-auto max-w-[190px] cursor-pointer"
              />
            </Link>
            <div className="flex flex-row flex-wrap items-center">
              <button className="text-accent px-6 py-2.5 border border-dark-white mr-6 cursor-pointer">
                Private Inquiry
              </button>
              <div className="p-4 cursor-pointer">
                <Image
                  src={MenuIcon}
                  alt="menu icon"
                  width={16}
                  height={12}
                  className="block"
                />
              </div>
            </div>
          </div>

          {/* <nav>
            <Link href="#">About Us</Link>
            <Link href="#">Contact us</Link>
            <Link href="#">Blog</Link>
            <Link href="#">FAQ</Link>
          </nav> */}
        </header>
        {/* hero */}
        <div className="relative z-0">
          <Image
            src={HeroImage}
            width={1440}
            height={900}
            alt="hero banner"
            className="w-full "
          />
          <h1 className="absolute top-[55%] left-[27%] -translate-x-1/2 -translate-y-1/2 w-[560px] h-[172px] text-heading-1 text-accent uppercase">
            financial ecosystem
          </h1>
        </div>
        {/* partners */}
        <div className="overflow-hidden w-full py-4 bg-accent">
          <div className="animate-marquee flex flex-row items-center justify-between gap-6">
            {[
              ...partners,
              ...partners,
              ...partners,
              ...partners,
              ...partners,
            ].map((partner, i) => (
              <Image
                src={partner}
                key={i}
                width={200}
                alt="partner brand"
                className="h-[56px]"
              />
            ))}
          </div>
        </div>
        <div className="max-w-1440 mx-auto">
          {/* who we are */}
          <div className="flex flex-row flex-wrap justify-between">
            <Image src={Section1} alt="who we are image" className="w-1/2" />
            <div className="pt-10 pl-16 pr-4 w-1/2">
              <h2 className="text-heading-2 text-heading mb-16 capitalize">
                Who We are
              </h2>
              <div className="relative py-2">
                <Image
                  src={Ornament}
                  width={50}
                  height={50}
                  alt="ornament"
                  className="absolute top-0 left-0 rotate-0"
                />
                <Image
                  src={Ornament}
                  width={50}
                  height={50}
                  alt="ornament"
                  className="absolute top-0 right-0 rotate-90"
                />
                <Image
                  src={Ornament}
                  width={50}
                  height={50}
                  alt="ornament"
                  className="absolute bottom-0 left-0 rotate-270"
                />
                <Image
                  src={Ornament}
                  width={50}
                  height={50}
                  alt="ornament"
                  className="absolute bottom-0 right-0 rotate-180"
                />
                <p className="text-display-r text-content m-20 text-justify">
                  Fuchase is a next-generation financial marketplace that
                  connects the key players of global capital markets. We provide
                  an environment where banks, brokers, fintechs, institutional
                  investors, and innovators can collaborate, trade, and
                  innovate. By combining cutting-edge technology, deep industry
                  expertise, and a global network, we serve as the strategic
                  bridge between liquidity, technology, and capital.
                </p>
              </div>
            </div>
          </div>
          {/* solutions */}
          <div className="px-16 py-28">
            <h1 className="capitalize text-heading-1 text-heading text-center">
              Solutions
            </h1>
            <div className="flex flex-row flex-wrap justify-center gap-24 mt-16">
              {Array.from(Array(10)).map((i) => (
                <div
                  className="p-6 relative shadow-[0px_32px_64px_rgba(0,0,0,0.14)] rounded-lg"
                  key={i}
                >
                  <Image
                    src={Ornament}
                    width={50}
                    height={50}
                    alt="ornament"
                    className="absolute top-6 left-6 rotate-0"
                  />
                  <Image
                    src={Ornament}
                    width={50}
                    height={50}
                    alt="ornament"
                    className="absolute top-6 right-6 rotate-90"
                  />
                  <div className="flex flex-col justify-between gap-8 pt-20">
                    <Image
                      src={GoldmanSachs}
                      alt="service logo"
                      width={200}
                      height={56}
                      className="mx-auto h-[56px]"
                    />
                    <p className="text-subtitle text-subtitle-r max-w-[400px] text-center mx-12">
                      Providing comprehensive, customized solutions for the
                      design, launch, and scalable growth of financial systems.
                    </p>
                    <div className="mx-auto flex flex-row flex-wrap items-center justify-between gap-3">
                      <Image
                        src={Location}
                        alt="location logo"
                        width={16}
                        height={20}
                      />
                      <span className="capitalize text-subtitle text-badge-t">
                        New York City
                      </span>
                    </div>
                    <button className="text-button-m w-fit text-primary py-2.5 px-6 bg-linear-to-b from-white/0 to-accent mx-auto cursor-pointer">
                      Invest for Future
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
          {/* who we serve */}
          <div className="flex flex-row flex-wrap justify-between">
            <Image src={Section2} alt="who we are image" className="w-1/2" />
            <div className="pt-10 pl-16 pr-4 w-1/2">
              <h2 className="text-heading-2 text-heading mb-16 capitalize">
                Who We serve
              </h2>
              <div className="relative py-2">
                <Image
                  src={Ornament}
                  width={50}
                  height={50}
                  alt="ornament"
                  className="absolute top-0 left-0 rotate-0"
                />
                <Image
                  src={Ornament}
                  width={50}
                  height={50}
                  alt="ornament"
                  className="absolute top-0 right-0 rotate-90"
                />
                <Image
                  src={Ornament}
                  width={50}
                  height={50}
                  alt="ornament"
                  className="absolute bottom-0 left-0 rotate-270"
                />
                <Image
                  src={Ornament}
                  width={50}
                  height={50}
                  alt="ornament"
                  className="absolute bottom-0 right-0 rotate-180"
                />
                <p className="text-display-r text-content m-20 text-justify">
                  Fuchase is a next-generation financial marketplace that
                  connects the key players of global capital markets. We provide
                  an environment where banks, brokers, fintechs, institutional
                  investors, and innovators can collaborate, trade, and
                  innovate. By combining cutting-edge technology, deep industry
                  expertise, and a global network, we serve as the strategic
                  bridge between liquidity, technology, and capital.
                </p>
              </div>
            </div>
          </div>
        </div>
        {/* {children} */}
        <footer>
          <div className="py-10 px-16 bg-primary">
            <div className="flex flex-row flex-wrap items-center justify-between max-w-1440 mx-auto">
              <span className="text-display-xxl text-accent">Get in touch</span>
              <div className="flex flex-col gap-6 justify-center items-center">
                <Image src={MailIcon} width={34} height={27} alt="mail icon" />
                <a
                  href="mailto:"
                  className="text-accent underline text-button-m"
                >
                  hello@fuchase.com
                </a>
              </div>
              <div className="flex flex-col gap-6 justify-center items-center">
                <Image src={PhoneIcon} width={30} height={30} alt="mail icon" />
                <a href="tel:+" className="text-accent underline text-button-m">
                  +1 (555) 000-0000
                </a>
              </div>
            </div>
          </div>
          <div className="px-16 pb-20 bg-secondary">
            <div className="py-14 flex flex-row flex-wrap justify-between max-w-1440 mx-auto">
              <div className="flex flex-col flex-wrap items-center gap-7">
                <Image src={Logo2} width={196} height={123} alt="logo2" />
                <a href="http://">
                  <Image
                    src={Linkedin}
                    width={30}
                    height={30}
                    alt="linkedin icon"
                    className="cursor-pointer"
                  />
                </a>
              </div>
              <div className="flex flex-row flex-wrap justify-between items-center gap-36">
                <ul>
                  <li className="text-display-xl text-accent pb-3">Company</li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      About
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Our Services
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Careers
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-display-l text-accent">
                      Our History
                    </Link>
                  </li>
                </ul>
                <ul>
                  <li className="text-display-xl text-accent pb-3">Company</li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      About
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Our Services
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Careers
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-display-l text-accent">
                      Our History
                    </Link>
                  </li>
                </ul>
                <ul>
                  <li className="text-display-xl text-accent pb-3">Company</li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      About
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Our Services
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Careers
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-display-l text-accent">
                      Our History
                    </Link>
                  </li>
                </ul>
                <ul>
                  <li className="text-display-xl text-accent pb-3">Company</li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      About
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Our Services
                    </Link>
                  </li>
                  <li className="pb-3">
                    <Link href="#" className="text-display-l text-accent">
                      Careers
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="text-display-l text-accent">
                      Our History
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
            <hr className="border border-dark-white" />
            <div className="py-2.5 flex flex-row flex-wrap justify-between items-center">
              <span className="block text-accent text-display-l">
                @2026 Fuchase
              </span>
              <p className="max-w-[741px] text-accent text-display-l">
                We connect elite financial institutions and visionary investors
                with transformative opportunities, exclusive partnerships, and
                next-generation financial infrastructure designed for those who
                operate at the highest level of global finance.{" "}
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
